---
- name: ensure utility present
  apt: name=sshpass state=present
- name: check for login
  command: sshpass -p {{raspi_config_auth_test_password}} ssh {{raspi_config_auth_test_username}}@localhost -o NoHostAuthenticationForLocalhost=yes "echo {{raspi_config_auth_test_string}}"
  register: auth_test
  changed_when: False
  failed_when: False
- name: optional warning
  debug: msg="{{raspi_config_auth_test_fail_msg}}"
  when: "raspi_config_auth_test_string == auth_test.stdout"
  changed_when: "raspi_config_auth_test_string == auth_test.stdout" # for highlighting purposes
  failed_when: "raspi_config_fail_on_auth_test and raspi_config_replace_user['name'] != None"
- name: additional info
  debug: msg="{{raspi_config_auth_test_replace_info}}"
  when: "raspi_config_auth_test_string == auth_test.stdout and raspi_config_replace_user['name'] != None"